ZON-3735: Set access attribute from K4 import
ZeitOnline/zeit.importer pull request #5
Opened 2017-02-24 15:16 UTC by rdrongow

2017-02-27 07:43 UTC, wosc requested changes
Im Prinzip sehr klar, das Mapping gehört aber finde ich in die zugehörige XML-Datei und nicht in den Code; was meinst Du?

2017-02-27 07:43 UTC, wosc commented on src/zeit/importer/article.py
> +#!/usr/bin/python
Ich glaub nicht dass diese Datei ausführbar ist...

2017-02-27 07:43 UTC, wosc commented on src/zeit/importer/article.py
> +# -*- coding: utf-8 -*-
Hmm da sollten wir dann wohl mal eine Coding-Style-Festlegung treffen. (Oder gibt's eine und ich kenn sie nur nicht?) Sonst mind. im vivi schreib ich nämlich `# coding: utf-8`

2017-02-27 07:43 UTC, wosc commented on src/zeit/importer/article.py
> +def map_access(context, text):
Das Mapping sollten wir denke ich mit in die http://cms-backend.zeit.de:9000/cms/work/data/access.xml schreiben, da stehen auch die C1-Schreibweisen schon drin.

2017-02-27 10:26 UTC, rdrongow commented on src/zeit/importer/article.py
> +def map_access(context, text):
Ah. Gute Idee, dass da zu hinterlegen. Allerdings sind die Werte nicht ganz kompatibel, bzw müssen wir uns entscheiden wie wir mit "nicht für online" umgehen. Einfach Online-Import skippen bei unbekannten Werten?

2017-02-27 10:29 UTC, rdrongow commented on src/zeit/importer/article.py
> +def map_access(context, text):
Ach nee. Das ergibt keinen Sinn... Das "nicht für online" soll ja bei der ersten Stufe noch da sein... (Wo ist die nächste Tischkante) ... 
Also: Ich könnte in der ersten Stufe die bekannten Werte mappen und die unbekannten lasse ich wie sie sind. In der zweiten Stufe skippe ich dann den Import für Artikel mit unbekannten Access Werten.

2017-02-28 10:42 UTC, wosc approved these changes
![open access](http://i.giphy.com/F1AA42Ryn9HG0.gif)

2017-02-28 10:42 UTC, merged